config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'


  resources :posts, except: [:destroy] do

    member do
      post :vote
    end


    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :categories, only: [:new, :create, :show]

  resources :users, only: [:show, :create, :edit, :update]



end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post, foreign_key: :post_id
  #has_many :votes, as: :voteable

  validates :body, presence: true

  # def total_votes
  #   self.up_votes - self.down_votes
  # end

  # def up_votes
  #   self.votes.where(vote: true).size
  # end

  # def down_votes
  #   self.votes.where(vote: false).size
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = Comment.new(params.require(:comment).permit(:body))
    @comment.post = @post
    #@comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.creator = User.find(session[:user_id])
    if @comment.save
      flash[:notice] = "Comment Added Successfully"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    vote = Vote.create(voteable: Comment.find(params[:id]), creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end

    # if vote.errors.any?
    #   flash[:error] = "Error Processing your Vote"
    # else
    #   flash[:notice] = "Vote accepted"
    # end

    # redirect_to :back
  end
end

app/views/comments/_comment.html.erb
<% show_post ||= false %>
<div class="row">
  <div class="span0 well text-center">
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
        <i class="icon-arrow-up"></i>
      <% end %>
      <br/>
      <span id="comment_<%= comment.id %>_votes"><%= comment.total_votes %> votes</span>
      <br/>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% else %>
      <%= comment.total_votes %> votes
    <% end %>
  </div>
  <div class="well span8">
    <em>"<%= comment.body %>"</em>
    <% if show_post %>
      on <%= link_to comment.post.title, post_path(comment.post) %>
    <% end %>
    <br/>
    <span class="quiet">
    posted by </span><%= link_to comment.creator.username, user_path(comment.creator) %> 
    <small> at <%= fix_time(comment.created_at) %></small>
  </div>
</div>

app/views/comments/vote.js.erb
$('#comment_<%= @comment.id %>_votes').html('<%= @comment.total_votes %> votes');