config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'


  resources :posts, except: [:destroy] do

    member do
      post :vote
    end


    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :categories, only: [:new, :create, :show]

  resources :users, only: [:show, :create, :edit, :update]



end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Slugable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  #has_many :votes, as: :voteable

  #after_validation :generate_slug

  validates :title, presence: true, length: {minimum: 5}
  validates :url, presence: true, uniqueness: true


  set_slugable_column :title
  # def total_votes
  #   self.up_votes - self.down_votes
  # end

  # def up_votes
  #   self.votes.where(vote: true).size
  # end

  # def down_votes
  #   self.votes.where(vote: false).size
  # end

  # def generate_slug
  #   the_slug = create_slug(self.title)
  #   post = Post.find_by(slug: the_slug)
  #   count = 2
  #   while post && post != self
  #     the_slug = append_suffix(the_slug, count)
  #     post = Post.find_by(slug: the_slug)
  #     count += 1
  #   end
  #   self.slug = the_slug
  # end

  # def append_suffix(str, count)
  #   if str.split('-').last.to_i != 0
  #     return str.split('-').slice(0...-1).join('-') + "-" + count.to_s
  #   else
  #     return str + "-" + count.to_s
  #   end
  # end

  # def create_slug(name)
  #   str = name.strip
  #   str.gsub!(/\s*[^A-Za-z0-9]\s*/, '-')
  #   str.gsub!(/-+/, '-')
  #   str.downcase
  # end

  # def to_param
  #   self.slug
  # end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]
  before_action :require_permission, only: [:edit, :update]

  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse
    respond_to do |format|
      format.html
      format.json { render json: @posts, only: [:title, :url] }
    end
  end

  def show
    @comment = Comment.new
    respond_to do |format|
      format.html
      format.json do
        comment_list = []
        @post.comments.each do |comment|
          entry = {body: comment.body, user: comment.creator.username}
          comment_list.push(entry)
        end
        render json: comment_list
      end
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = User.find(session[:user_id])

    if @post.save
      flash[:notice] = "Your Post was Created Successfully"
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @post.update(post_params)
    if @post.save
      flash[:notice] = "Your Post was Edited Successfully"
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def vote
    vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  private

    def set_post
      #@post = Post.find(params[:id])
      @post = Post.find_by(slug: params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :url, :description, category_ids: [])
    end

    def require_permission
      access_denied unless logged_in? && (current_user.admin? || current_user == @post.creator)
    end
end

app/views/posts/_post.html.erb
<div class="row">
  <div class="span0 well text-center">
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
        <i class="icon-arrow-up"></i>
      <% end %>
      <br/>
      <span id='post_<%= post.slug %>_votes'><%= post.total_votes %> votes</span>
      <br/>
      <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% else %>
      <%= post.total_votes %> votes
    <% end %>
  </div>
  <div class="span8 well">
    <%= render post.categories %>
    <h4><%= link_to post.title, fix_url(post.url) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class="quiet">Posted by </span> <%= link_to post.creator.username, user_path(post.creator) %>
      <small>at <%= fix_time(post.created_at) %></small>
    </p>
    <small>
      <span>
        <%= link_to("#{post.comments.size} comments", post_path(post)) %>
      </span>
      <% if logged_in? %>
        <span>
          <%= link_to "Edit", edit_post_path(post) %>
        </span>
      <% end %>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: "Edit a Post" %>

<%= render 'shared/form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: "Create a New Post" %>

<%= render 'shared/form' %>

app/views/posts/show.html.erb
<% if logged_in? %>
  <p class="pull-right">
    [ <%= link_to "Edit this post", edit_post_path(@post) %> ]
  </p>
<% end %>

<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %>
</p>

<hr/>

<% if logged_in? %>
  <%= render 'shared/displayErrors', object: @comment %>

  <%= form_for [@post, @comment] do |f| %>
    <div class="control-group">
      <%= f.label :body, "Post a Comment" %>
      <%= f.text_area :body, rows: 3, class: "span4" %>
      <br/>
    </div>
    <%= f.submit "Post Comment", class: 'btn btn-primary' %>
  <% end %>
<% else %>
  <h5><%= link_to "Register", register_path %> or <%= link_to "Login", login_path %> to Post a Comment</h5>
<% end %>

<h5>Comments:</h5>
<% @post.comments.sort_by{|x| x.total_votes}.reverse.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>

app/views/posts/vote.js.erb
$('#post_<%= @post.slug %>_votes').html('<%= @post.total_votes %> votes');