config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'


  resources :posts, except: [:destroy] do

    member do
      post :vote
    end


    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :categories, only: [:new, :create, :show]

  resources :users, only: [:show, :create, :edit, :update]



end

app/models/category.rb
class Category < ActiveRecord::Base
  include Slugable

  has_many :post_categories
  has_many :posts, through: :post_categories

  #after_validation :generate_slug

  validates :name, presence: true

  set_slugable_column :name
  # def generate_slug
  #   the_slug = create_slug(self.name)
  #   post = Category.find_by(slug: the_slug)
  #   count = 2
  #   while post && post != self
  #     the_slug = append_suffix(the_slug, count)
  #     post = Category.find_by(slug: the_slug)
  #     count += 1
  #   end
  #   self.slug = the_slug
  # end

  # def append_suffix(str, count)
  #   if str.split('-').last.to_i != 0
  #     return str.split('-').slice(0...-1).join('-') + "-" + count.to_s
  #   else
  #     return str + "-" + count.to_s
  #   end
  # end

  # def create_slug(name)
  #   str = name.strip
  #   str.gsub!(/\s*[^A-Za-z0-9]\s*/, '-')
  #   str.gsub!(/-+/, '-')
  #   str.downcase
  # end

  # def to_param
  #   self.slug
  # end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create]
  before_action :require_admin, only: [:new, :create]
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params.require(:category).permit(:name))
    if @category.save
      flash[:notice] = "Categoy created Successfully"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find_by(slug: params[:id])
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_categoryForm.html.erb
<% if @category.errors.any? %>
  <%= render 'shared/displayErrors', object: @category %>
<% end %>

<div class="well">
  <%= form_for @category do |f| %>
    <div class='control-group'>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit "Create Category", class: 'btn btn-success' %>
  <% end %>
</div>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: "New Category" %>

<%= render 'categoryForm' %>

app/views/categories/show.html.erb
<% header = link_to('All Posts', posts_path) + " &raquo; #{@category.name}".html_safe %>

<%= render 'shared/content_title', title: header %>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>